project_id = "lodpoepylygsryjdkqjg"

[functions.list-users]
verify_jwt = false

[functions.create-users]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.manage-auth-users]
verify_jwt = false

[functions.rtne-check-or-create]
verify_jwt = true

[functions.rtne-process-enrichment]
verify_jwt = true

[functions.rtne-admin-override]
verify_jwt = true

[functions.chrome-extension-login]
verify_jwt = false

[functions.chrome-extension-validate]
verify_jwt = false

[functions.chrome-extension-prospects]
verify_jwt = false

[functions.lusha-enrich]
verify_jwt = true
